services:
  db:
    image: postgres:18-alpine
    container_name: motorcycle_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: motorcycle_shop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/pg_hba.conf:/etc/postgresql/pg_hba.conf
    networks:
      - motorcycle_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d motorcycle_shop"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    command: >
      postgres
      -c listen_addresses=*
      -c password_encryption=scram-sha-256
    tmpfs:
      - /var/run/postgresql

  redis:
    image: redis:7-alpine
    container_name: motorcycle_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - motorcycle_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build: ./backend
    container_name: motorcycle_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: motorcycle_shop
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: your_jwt_secret_key_change_in_production
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
      - frontend_images:/app/frontend-images
    networks:
      - motorcycle_network

  frontend:
    build: ./frontend
    container_name: motorcycle_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - frontend_images:/usr/share/nginx/html/images
    networks:
      - motorcycle_network

volumes:
  postgres_data:
  frontend_images:

networks:
  motorcycle_network:
    driver: bridge